version: '3'

services:
  server:
    build: .
    command: ./server
    networks:
      - mark
  client:
    build: .
    command: ./client
    networks:
      - mark
    depends_on:
      - server
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mark
    depends_on:
      - client
      - server
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/all.yml:/etc/grafana/provisioning/dashboards/all.yml
      #- ./grafana/app_dashboard.json:/var/lib/grafana/dashboards/app_dashboard.json
    ports:
      - "3000:3000"
    networks:
      - mark
    depends_on:
      - prometheus
networks:
  mark:
