version: '3'

services:
  app:
    build: .
    networks:
      - mark
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mark
    depends_on:
      - app
  grafana:
    image: grafana/grafana
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./all.yml:/etc/grafana/provisioning/dashboards/all.yml
      - ./app_dashboard.json:/var/lib/dashboards/app_dashboard.json
    ports:
      - "3000:3000"
    networks:
      - mark
    depends_on:
      - prometheus
networks:
  mark:
