{
 "title": "App",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Reader No Messages Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_reader_no_messages_available[5m])"
    }
   ]
  },
  {
   "title": "Writer Stream Full",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_writer_stream_full[5m])"
    }
   ]
  },
  {
   "title": "Reader/Writer Batch Rate",
   "type": "graph",
   "description": "batch rate for reader and writer",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(app_reader_batch[5m])" },
    { "expr": "rate(app_writer_batch[5m])" }
   ]
  }
 ]
}