{
 "title": "Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Client Bytes Sent Rate",
   "type": "graph",
   "description": "client bytes sent per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(app_client_bytes_sent[5m])"
    }
   ]
  },
  {
   "title": "Server Bytes Received Rate",
   "type": "graph",
   "description": "server bytes received per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(app_server_bytes_recv[5m])"
    }
   ]
  },
  {
   "title": "Client Messages Sent Rate",
   "type": "graph",
   "description": "client messages sent per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_client_message_sent[5m])"
    }
   ]
  },
  {
   "title": "Server Messages Received Rate",
   "type": "graph",
   "description": "server messages received rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_server_message_recv[5m])"
    }
   ]
  },
  {
   "title": "Client Send Error Rate",
   "type": "graph",
   "description": "client send errors per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_client_send_error[5m])"
    }
   ]
  },
  {
   "title": "Server Receive Error Rate",
   "type": "graph",
   "description": "server receive errors per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_server_recv_error[5m])"
    }
   ]
  },
  {
   "title": "Server Receive EOF Rate",
   "type": "graph",
   "description": "server receive error EOF from client per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_server_recv_error_eof[5m])"
    }
   ]
  }
 ]
}