{
 "title": "Server",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Server Messages Received",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_server_message_recv[5m])"
    }
   ]
  },
  {
   "title": "Server Bytes Received",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_server_bytes_recv[5m])"
    }
   ]
  },
  {
   "title": "Server Receive EOF",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_server_recv_error_eof[5m])"
    }
   ]
  },
  {
   "title": "Server Receive Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_server_recv_error[5m])"
    }
   ]
  }
 ]
}